version: '3'
services:
  front:
    build:
      context: .
      dockerfile: ./flutterApp/Dockerfile
      args:
        - API_PROTOCOL=https
        - API_PORT=443
        - API_HOST=localhost
        - API_PATH=/api
    ports:
      - 8081:80
    networks:
      - intr
      - extr
  nginx:
    image: nginx
    build:
      context: .
      dockerfile: ./apiApp/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ./nginx/pkcs8_key.pem
        target: /etc/nginx/conf.d/server.key
      - type: bind
        source: ./nginx/server.cert
        target: /etc/nginx/conf.d/server.cert
    networks:
      - extr
      - intr
networks:
  intr:
    internal: true
  extr:
    internal: false