services:
  back:
    build:
      context: .
      dockerfile: ./apiApp/Dockerfile

  nginx:
    image: nginx
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ./nginx/pkcs8_key.pem
        target: /etc/nginx/conf.d/server.key
      - type: bind
        source: ./nginx/server.crt
        target: /etc/nginx/conf.d/server.crt
      - type: bind
        source: ./flutterApp/bank_web_app/build/web
        target: /usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    depends_on:
      - back