version: '3'
services:
  nginx:
    image: nginx
    build:
      context: .
      dockerfile: ./apiApp/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ./nginx/pkcs8_key.pem
        target: /etc/nginx/conf.d/server.key
      - type: bind
        source: ./nginx/server.cert
        target: /etc/nginx/conf.d/server.cert
